// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFCObP3sCt21wg0qxsDFq2tXIv7JpPDw4',
    appId: '1:1074894448306:web:53e7637216c2ef54cc0bab',
    messagingSenderId: '1074894448306',
    projectId: 'mdpgold-4dd03',
    authDomain: 'mdpgold-4dd03.firebaseapp.com',
    databaseURL: 'https://mdpgold-4dd03-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-4dd03.firebasestorage.app',
    measurementId: 'G-B29LS8HRH0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuJtJTMI0bAJIxyVERkM2_96NLtM31X78',
    appId: '1:1074894448306:android:7ff30a56918cfd2ecc0bab',
    messagingSenderId: '1074894448306',
    projectId: 'mdpgold-4dd03',
    databaseURL: 'https://mdpgold-4dd03-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-4dd03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYq1xgCOsCavXmu1wiCF40OY184Q3_oD8',
    appId: '1:1074894448306:ios:3d0284122e808287cc0bab',
    messagingSenderId: '1074894448306',
    projectId: 'mdpgold-4dd03',
    databaseURL: 'https://mdpgold-4dd03-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-4dd03.firebasestorage.app',
    iosBundleId: 'com.example.mdpGold',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYq1xgCOsCavXmu1wiCF40OY184Q3_oD8',
    appId: '1:1074894448306:ios:3d0284122e808287cc0bab',
    messagingSenderId: '1074894448306',
    projectId: 'mdpgold-4dd03',
    databaseURL: 'https://mdpgold-4dd03-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-4dd03.firebasestorage.app',
    iosBundleId: 'com.example.mdpGold',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFCObP3sCt21wg0qxsDFq2tXIv7JpPDw4',
    appId: '1:1074894448306:web:129601f69cee3c1fcc0bab',
    messagingSenderId: '1074894448306',
    projectId: 'mdpgold-4dd03',
    authDomain: 'mdpgold-4dd03.firebaseapp.com',
    databaseURL: 'https://mdpgold-4dd03-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-4dd03.firebasestorage.app',
    measurementId: 'G-KBTG2S0B1G',
  );
}
