// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB25cg5uOVxPaIEZnnq06snptbf_MJSCf8',
    appId: '1:460659539432:web:0851d3bc761f3129ffb85d',
    messagingSenderId: '460659539432',
    projectId: 'notes-e9b8c',
    authDomain: 'notes-e9b8c.firebaseapp.com',
    storageBucket: 'notes-e9b8c.firebasestorage.app',
    measurementId: 'G-Y9C0CYT7WV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtY_l2ayqSuW9OOyN1uIFFgqirDngk14U',
    appId: '1:460659539432:android:0084721b9a9a7483ffb85d',
    messagingSenderId: '460659539432',
    projectId: 'notes-e9b8c',
    storageBucket: 'notes-e9b8c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv2zj43wenMpZkBNYPuR_GkCOVmJaS424',
    appId: '1:460659539432:ios:5f4608d7a93e93e2ffb85d',
    messagingSenderId: '460659539432',
    projectId: 'notes-e9b8c',
    storageBucket: 'notes-e9b8c.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv2zj43wenMpZkBNYPuR_GkCOVmJaS424',
    appId: '1:460659539432:ios:5f4608d7a93e93e2ffb85d',
    messagingSenderId: '460659539432',
    projectId: 'notes-e9b8c',
    storageBucket: 'notes-e9b8c.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB25cg5uOVxPaIEZnnq06snptbf_MJSCf8',
    appId: '1:460659539432:web:234e4f1b59703001ffb85d',
    messagingSenderId: '460659539432',
    projectId: 'notes-e9b8c',
    authDomain: 'notes-e9b8c.firebaseapp.com',
    storageBucket: 'notes-e9b8c.firebasestorage.app',
    measurementId: 'G-13C7Z7S972',
  );
}
